### ISSUE TITLE
Add support for Debian 12 - bookworn

### ISSUE THREAD

**Issue by NicoAs** [NicoAs/k3s-ansible#1]
## Expected Behavior

Update for raspberry pi with Debian 12 - bookworm

## Current Behavior

Only Debian 11 is actually supported

## Steps to Reproduce

Host hae Debian OS

1.  ansible-playbook site.yml

## Context (variables)

Operating system: Debian 12

Hardware: Raspberry 4

### Variables Used

`all.yml`

```yml
k3s_version: ""
ansible_user: NA
systemd_dir: ""

flannel_iface: ""

apiserver_endpoint: ""

k3s_token: "NA"

extra_server_args: ""
extra_agent_args: ""

kube_vip_tag_version: ""

metal_lb_speaker_tag_version: ""
metal_lb_controller_tag_version: ""

metal_lb_ip_range: ""
```

### Hosts

`host.ini`

```ini
[master]
IP.ADDRESS.ONE
IP.ADDRESS.TWO
IP.ADDRESS.THREE

[node]
IP.ADDRESS.FOUR
IP.ADDRESS.FIVE

[k3s_cluster:children]
master
node
```

## Possible Solution

- [ ] I've checked the [General Troubleshooting Guide](https://github.com/techno-tim/k3s-ansible/discussions/20)
